export enum RolesEnum {
  SUPER_ADMINISTRADOR = 'SUPER ADMINISTRADOR',
  ADMINISTRADOR = 'ADMINISTRADOR',
  ADMINISTRADOR_JOSH = 'ADMINISTRADOR JOSH',
  RECEPCION = 'RECEPCION',
  MEDICO = 'MEDICO',
  LABORATORISTA = 'LABORATORISTA',
  ALMACENISTA = 'ALMACENISTA',
  TRABAJO_SOCIAL = 'TRABAJO SOCIAL',
  CONSULTA = 'CONSULTA',
  CONSULTA_BI = 'CONSULTA BI',
}
